### ISSUE TITLE
Iteration 1 Feedback

### ISSUE THREAD

**Issue by kaesrel** [koonwill/ku-polls#24]
* No project table with spreadsheet view that contains all tasks
* The task board should be named "Iteration 1" instead of "View"
* The poll "Dangerous from Motorcycle Taxi rider in KU" should be written as a question (e.g. "Are motorcycle taxis in KU dangerous?"). 
  * The choices should also be rewritten (from "Dangerous, Should Fix" to something like "so dangerous, this issue should be dealt with immediately")
* The poll "Few Shuttle bus in KU" should be rewritten as "Are there too few shuttle bus in KU?".
  * Also, what is the differences of the choices between "ok" and "enough"?

**Comment by koonwill** [comment]
* No project table with spreadsheet view that contains all tasks
* The task board should be named "Iteration 1" instead of "View"

Fix : https://github.com/users/koonwill/projects/1/views/8

**Comment by koonwill** [comment]
* The poll "Dangerous from Motorcycle Taxi rider in KU" should be written as a question (e.g. "Are motorcycle taxis in KU dangerous?"). 
  * The choices should also be rewritten (from "Dangerous, Should Fix" to something like "so dangerous, this issue should be dealt with immediately")
* The poll "Few Shuttle bus in KU" should be rewritten as "Are there too few shuttle bus in KU?".
  * Also, what is the differences of the choices between "ok" and "enough"?
 
Fix : Fix database in iteration 3 wait for merge.

**Comment by koonwill** [comment]
All Fix
